### ISSUE TITLE
Error in platform

### ISSUE THREAD

**Issue by sobrito** [2stacks/docker-freeradius#1]
In my environment i use Window to debug and develop and linux to create a image, i was has problems with your source code: 

standard_init_linux.go:185: exec user process caused "no such file or directory"
Can be solved with dos2unix:

Changing it:
`RUN apk --update add freeradius freeradius-mysql freeradius-eap bash dos2unix`

and changing it:

`
RUN chmod +x /usr/local/bin/wait-for-it.sh \
    && dos2unix /usr/local/bin/wait-for-it.sh

ADD ./start.sh /start.sh
RUN chmod +x /start.sh \
    && dos2unix /start.sh
`

I do not received this error again

**Comment by 2stacks** [comment]
Thanks.  I never tested against Windows OS.
