### ISSUE TITLE
Permission Warning causing error

### ISSUE THREAD

**Issue by sobrito** [2stacks/docker-freeradius#2]
In my environment i use Window to debug and develop and linux to create a image, i was has problems with your source code:

Errors reading /etc/raddb/dictionary: dict_init: Dictionary "/etc/raddb/dictionary" is globally writable.  Refusing to start due to insecure configuration.

Can be solved changing to the correct file permission:

`

RUN chmod 0640 /etc/raddb/dictionary \
    && chmod 0640 /etc/raddb/*.conf \
    && chmod 0640 -R /etc/raddb/mods-available \
    && chmod 0640 -R /etc/raddb/mods-enabled \
    && chmod 0640 -R /etc/raddb/policy.d \
    && chmod 0640 -R /etc/raddb/sites-available \
    && chmod 0640 -R /etc/raddb/sites-enabled

RUN chown -R root:radius /etc/raddb

`

After change this, i do not received this error again

**Comment by 2stacks** [comment]
Can you tell me more about your ENV.  I dont have this issue with Docker-CE on Ubuntu.

**Comment by 2stacks** [comment]
I wasn't able to reproduce this issue.  If you pull the container image from docker hub you shouldn't have an issue as the files in /etc/raddb were added to the alpine image with the correct permissions.  If you are building the image yourself from the code repository it may be an issue with the permissions your OS gives to the files when the repository is cloned.
