### ISSUE TITLE
Where is the configuration file? No search

### ISSUE THREAD

**Issue by bbhxwl** [2stacks/docker-freeradius#23]
Where is the configuration file? No search

Or have you already set this option?

**Comment by 2stacks** [comment]
/etc/raddb is added to the container when it is built.

**Comment by bbhxwl** [comment]
I can ask you, the default setting allows the number of people online at the same time?

**Comment by 2stacks** [comment]
It should but you need to implement this with Radius Groups in your
database.

**Comment by 2stacks** [comment]
If you want to customize Freeradius you'll have to rebuild the container. If you want to add configuration to the mysql database just connect to it with a mysql client.
