### ISSUE TITLE
No database initialization script?

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [2stacks/docker-freeradius#24]
I'm getting this error when running `docker-compose up -d`

`rlm_sql (sql): Processing generate_sql_clients
rlm_sql (sql) in generate_sql_clients: query is SELECT id, nasname, shortname, type, secret, server FROM nas
rlm_sql (sql): Reserved connection (0)
rlm_sql (sql): Executing select query: SELECT id, nasname, shortname, type, secret, server FROM nas
rlm_sql (sql): rlm_sql_mysql: ERROR 1146 (Table 'radius.nas' doesn't exist): 42S02
Failed to load clients from SQL
/etc/raddb/mods-enabled/sql[20]: Instantiation failed for module "sql"`

**Comment by 2stacks** [comment]
Its probably a symlink issue.  Look at the Readme.  It should have some
info.

**Comment by Karlheinzniebuhr** [comment]
Solved by cloning the repository from github. I executed `docker pull 2stacks/freeradius` directly and it seems like dockerhub doesn't pull the radius.sql file

**Comment by 2stacks** [comment]
Ah, yeah the freeradius container doesn't include all of the mysql
dependencies in the container.  That file has to be mounted as a volume in
a separate mysql container.
