### ISSUE TITLE
Error when get your repository

### ISSUE THREAD

**Issue by sobrito** [2stacks/docker-freeradius#4]
When i try get your image, i receive this error:
`
pull access denied for freeradius, repository does not exist or may require 'docker login'.

`
When i execute: 

> sudo docker run -d -t freeradius -p 1812/udp:1812/sdp -p 1813/udp:1813/udp -e DB_HOST=10.224.100.12 -e DB_PORT=32768 -e DB_PASS=c92a666087ae3a8131f371da913a5fa3 -e RADIUS_KEY=d16773ea3ddf0835f72cb11ca9459934 -e RAD_CLIENTS=10.224.100.0/24   2stacks/freeradius

I don't know, if this is a error in permission on docker or in github (a private repo on docker, with open source code on github)

If this project is private, i will create my version of freeradius-server image, but if is public, i send to you my report and suggestion to try contrib with this project.

**Comment by 2stacks** [comment]
Its a public docker image but you may still have to login to Docker hub.
